### ISSUE TITLE
Cannot run a query on Athena

### ISSUE THREAD

**Issue by ori-n** [wix/quix#185]
I want to try quix on Athena but I couldn't get it to work. I used the docker-compose without editing it.
I wanted to ask if a presto container is really needed if I'm using Athena, or can I remove it?
When I tried to run a simple "SELECT 1" query I got a "Connection Lost" error in the UI, and did not see errors while I followed the docker compose logs. I will be happy for some help.

Thanks.

**Comment by frolovv** [comment]
hey @ori-n 

you are correct, presto container isn't necessary if you want to try athena (cc @sthuck ) 

also, did you follow [this guide](https://wix.github.io/quix/docs/athena) to setup user/permissions and .env file?

**Comment by ori-n** [comment]
Yes I followed the guide. 

Here is what I did:

I used the docker-compose.prebuilt.yml. I removed the presto database from the compose file and started the containers.  This is the env file I used:
`AUTH_TYPE=fake
MODULES=athena
MODULES_ATHENA_ENGINE=athena
MODULES_ATHENA_OUTPUT=s3://my-bucket/my-folder/quix_output
MODULES_ATHENA_REGION=us-east-1
MODULES_ATHENA_DATABASE=default
MODULES_ATHENA_AWS_ACCESS_KEY_ID=my_acceess_key
MODULES_ATHENA_AWS_SECRET_KEY=my_secret_key
MODULES_ATHENA_DB_EMPTY_TIMEOUT=60000
MODULES_ATHENA_DB_REQUEST_TIMEOUT=10000`

I tried a few times. In some cases I could not login and got this error:
> error: { Error: ER_NO_SUCH_TABLE: Table 'quix.users' doesn't exist
In others I got to the "connection lost" error

**Comment by sthuck** [comment]
Hi Ori! 

I'm afraid our `env-example` file had a mistake in it (now fixed). Specifically if you have those two lines in your `.env`:
```
BACKEND_INTERNAL_URL=
BACKEND_PUBLIC_URL=
```
Please comment them out
```
#BACKEND_INTERNAL_URL=
#BACKEND_PUBLIC_URL=
```
I believe this should fix the issue with querying Athena. 

The 2nd error you reported:
> `error: { Error: ER_NO_SUCH_TABLE: Table 'quix.users' doesn't exist`
I believe is unrelated, and a lot more weird. 

I would appreciate if you could run the following commands and put here the output:
`docker exec quix_db_1 mysql quix -e "show tables"`
`docker exec quix_db_1 mysql quix -e "select * from migrations"`
`docker exec quix_db_1 mysql quix -e "select * from version_metadata"`

**Comment by ori-n** [comment]
I posted the env file I used (above). It doesn't have the two lines in it.
Can you look the file I posted - is there anything wrong with it?

As for the users table - I think the error happens because I tried to login before the table was created. 
The problem is that when the DB is created the error remains - to fix it I had run installation again

**Comment by frolovv** [comment]
just followed [the athena guide](https://wix.github.io/quix/docs/athena) and discovered that there was a missing permission for iam policy.

commit that fixed it : 
https://github.com/wix/quix/commit/488768102dd506049891ca1a68d6b7e9ffd2e113#diff-fe7082d90928919f3ce8957f972618cd

correct policy is : 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::your-bucket-name/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetBucketLocation",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::your-bucket-name"
            ]
        }
    ]
}
```

also adding copy of my .env file : 
```properties
MODULES=athena

MODULES_ATHENA_ENGINE=athena
MODULES_ATHENA_OUTPUT=s3://BUCKET_NAME/sub-folder/sub-sub-folder/
MODULES_ATHENA_REGION=us-east-1
MODULES_ATHENA_DATABASE=default
MODULES_ATHENA_AWS_ACCESS_KEY_ID=KEY
MODULES_ATHENA_AWS_SECRET_KEY=SECRET
```

**Comment by ori-n** [comment]
All seems OK in the configuration. I looked a little bit at the browser logs:
my-host:3000/api/db/explore returns 404 - and this is also what the db explorer shows

**Comment by antonpod** [comment]
@ori-n are you able to run queries?

**Comment by ori-n** [comment]
no

**Comment by sthuck** [comment]
@antonpod see that his request is going to `my-host:3000/api/db/explore` instead of `my-host:3000/api/db/athena/explore`, can you take a look?

**Comment by frolovv** [comment]
@ori-n as i understand your ticket helped us to uncover a few critical bugs, tnx for starting this conversation! 

i'm closing the ticket for now, if you have any more issues please open a new issue or talk to us directly via http://wix-quix.slack.com/
